### ISSUE TITLE
Shrinkwrap Gradle - Could not determine java version from '11.0.1' - exception while running  Arquillian Integration Test

### ISSUE THREAD

**Issue by mswdev1823** [shrinkwrap/shrinkwrap#118]
Hello, I am buidling an Arquillian Integration Test with shrinkwrap-resolver-impl-**gradle** v3.1.3 using Gradle 4.10.2, OpenJDK 11.0.1, Wildfly 14.0.1 on Windows 10.

I am using both Maven and Gradle. The maven version of test runs fine, but the Gradle version of the test fails with the following exception.

I have looked at https://docs.gradle.org/current/javadoc/org/gradle/api/JavaVersion.html and I don't think it is related to Gradle Tooling API not supporting Open JDK 11.0.1 but I could be mistaken.

```
 java.lang.RuntimeException: Could not invoke deployment method: public static org.jboss.shrinkwrap.api.spec.WebArchive ...AppConfigBeanITest.createDeployment()

        Caused by:
        java.lang.reflect.InvocationTargetException

            Caused by:
            java.lang.IllegalArgumentException: Could not determine java version from '11.0.1'.
                at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
                at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
                at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
                at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:57)
                at org.gradle.tooling.internal.consumer.ConnectorServices.createConnector(ConnectorServices.java:35)
                at org.gradle.tooling.GradleConnector.newConnector(GradleConnector.java:85)
                at org.jboss.shrinkwrap.resolver.impl.gradle.GradleRunner.getEffectiveDependencies(GradleRunner.java:21)
                at org.jboss.shrinkwrap.resolver.impl.gradle.GradleStrategyStage.asList(GradleStrategyStage.java:46)
                at org.jboss.shrinkwrap.resolver.impl.gradle.GradleStrategyStage.as(GradleStrategyStage.java:34)
```

**Comment by mswdev1823** [comment]
@MatousJobanek, this is probably related to Shrinkwrap use of old version,  4.0.1 of Gradle tooling API. 
Can we please have it upgraded to version 4.3 to support OpenJDK 11.0.1?

<dependency>
    <groupId>org.gradle</groupId>
    <artifactId>gradle-tooling-api</artifactId>
    <version>4.3</version>
</dependency>

**Comment by petrberan** [comment]
I know this is a 6 year old issue, but Resolver has been upgraded to use Gradle API version 8.5 in version 3.3.0 - https://github.com/shrinkwrap/resolver/pull/194
