### ISSUE TITLE
ShrinkWrap Build Fails in JDK9

### ISSUE THREAD

**Issue by ALRubinger** [shrinkwrap/shrinkwrap#130]
Environment:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/alr/.sdkman/candidates/maven/current
Java version: 9.0.4, vendor: Oracle Corporation, runtime: /Users/alr/.sdkman/candidates/java/9.0.4-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "Mac"
```

Tests failing on build:
```
testAddResourceStringTargetResourceFromJar(org.jboss.shrinkwrap.impl.base.spec.JavaArchiveImplTestCase)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.IllegalArgumentException: /java.base/java/lang/String.class was not found in any available ClassLoaders
	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addNestedJarFileResource(ContainerBase.java:810)
	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsResource(ContainerBase.java:1149)
	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsResource(ContainerBase.java:1069)
	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsResource(ContainerBase.java:1056)
	at org.jboss.shrinkwrap.impl.base.test.DynamicContainerTestBase.testAddResourceStringTargetResourceFromJar(DynamicContainerTestBase.java:599)
```

This is because of ClassLoading changes introduced into the JDK. Update ShrinkWrap to maintain compatibility.

**Comment by ALRubinger** [comment]
Done in #134
