### ISSUE TITLE
Jacoco instrumentation fails on modern JVMs

### ISSUE THREAD

**Issue by ALRubinger** [shrinkwrap/shrinkwrap#131]
```
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2013)
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
```

This from JDK 14, for instance (works fine on JDK9):

```
alr@alr-saturator shrinkwrap % mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/alr/.sdkman/candidates/maven/current
Java version: 14.0.2, vendor: Oracle Corporation, runtime: /Users/alr/.sdkman/candidates/java/14.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

**Comment by ALRubinger** [comment]
Done through PR #134
